### ISSUE TITLE
WEMO Maker reports door open when closed and vice versa

### ISSUE THREAD

**Issue by TharuMCD** [rudders/homebridge-platform-wemo#136]
Dear community,

I have successfully installed the platform onto Homebridge on a Windows 10 machine.  Brilliant piece of work - thank you very much for sharing this.  

One glitch is that Homekit reports the garage door being open when actually it is shut and vice-versa.  I suspect this is because the sensor is a reed switch which triggers when the door opens and is not triggered when closed.  In the Wemo App, I can set notifications to interpret the not triggered as the door is closed, and the triggered as being open.

I tried reversing the wiring of the sensor, but it does not change the status in the Wemo App or HomeKit App.  Is there any way of adding a configuration line to reverse the sensor interpretation?  Logistically, I cannot change the location of the magnetic reed switch such that the contacts are together when the door is closed - which of course would be the mechanical solution.  Hoping for a software / digital workaround if possible.

With kind regards,
Michael.

**Comment by DMBlakeley** [comment]
Hi Michael,

Although the software could probably be patched, there are a couple of reasons that you should have a garage closed switch.  First, is that you really want to know if the door is closed (and your garage is secure) rather than NOT closed (where you have not idea).  Second, it is a bit of a safety consideration as you really have no idea if the door properly closed or was obstructed by something on the way down.

Would it be possible to add an additional magnetic reed switch?  I have the the magnet on the top side of my door and the reed switch mounted on the garage door frame.  The Wemo Maker is installed right next to the garage door opener.  So routing a cable from the switch to the Maker was quite easy.  This has worked with no issue.

Regards,
Doug

**Comment by TharuMCD** [comment]
Thanks.

Your comments are all very logical.  I have one those up and over garage doors by Garador.  So the motor unit is suspended from the ceiling on the metal railing track of the whole setup – basically in the centre of the ceiling of the garage.  I looked at options alternative places to fit the sensor – but was put off by the fact that I then have to run a cable from the sensor such a long distance to the garage door motor unit where the Wemo Maker is.

While an imperfect solution, I decided to keep the sensor attached to a portion of the track.  I will have another look around to see if I can neatly re-wire everything.  Guess I was looking for a quick software fix – and thought it might have just been an optional parameter rather than any major software patch!

Kind regards,
Michael.

**Comment by DMBlakeley** [comment]
Here are a couple of pictures of how I mounted the switch as well as the Wemo Maker.  I mounted the switch to the side, however, there is no reason that it could not have been installed closer to the middle of the door to reduce the cable run.

![img_1050](https://user-images.githubusercontent.com/29609206/39212927-242eda4a-47de-11e8-85b1-8813fbf11854.jpg)
![img_1051](https://user-images.githubusercontent.com/29609206/39212934-2771ecec-47de-11e8-986e-d16e97df5edf.jpg)

**Comment by TharuMCD** [comment]
Thanks – that is very useful.  Will give it a go either this weekend or next, and let you know how things go.

Kind regards,
Michael.

**Comment by devbobo** [comment]
Closing this, since it's simply a matter of not using a reed switch or similar.
