### ISSUE TITLE
Wemo Air Purifiers & other Wemo Appliances -multiple device issue

### ISSUE THREAD

**Issue by Zeate22211** [rudders/homebridge-platform-wemo#45]
I notice I have to unplug one of my Wemo Air Purifiers when I launch Homebridge or I receive this error:

[6/5/2016, 8:25:43 AM] [WeMo Platform] Initializing platform accessory 'AirPurifier'...
Not implemented
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:219
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: a113195d-ba23-4ac5-a8bb-8922a4e6aef6
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:219:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:346:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:113:13)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

==================================
These Wemo Air Purifiers have the same Friendly Name and when Homebridge is detecting it just shows AirPurifier as the accessory name instead of the names I have setup in Belkin Wemo App.   This will probably be an issue with users who have multiple sets of the Wemo appliances.  The larger Wemo Heater will always shows up as HeaterA and smaller one will be called HeaterB.  I have those devices as well.

Here is a dump:

DeviceID="65541"
presentationURL="/pluginpres.html"
binaryState="0"
serialNumber="221424S000005A"
friendlyName="AirPurifier"
macAddress="94103E598D98"
brandName="Holmes"
DeviceFWVersion="V1.01"
modelDescription="Belkin Plugin Socket 1.0"
modelName="AirPurifier"
modelURL="http://www.belkin.com/plugin/"
manufacturer="Belkin International Inc."
deviceType="urn:Belkin:device:AirPurifier:1"
firmwareVersion="WeMo_WW_2.00.10486.PVT-OWRT-Smart"
iconVersion="1|49153"
manufacturerURL="http://www.belkin.com"
UDN="uuid:AirPurifier-1_0-221424S000005A"
modelNumber="1.0"
UPC="123456789"

DeviceID="65541"
presentationURL="/pluginpres.html"
binaryState="0"
serialNumber="221424S00002F2"
friendlyName="AirPurifier"
macAddress="94103E5997F8"
brandName="Holmes"
DeviceFWVersion="V1.01"
modelDescription="Belkin Plugin Socket 1.0"
modelName="AirPurifier"
modelURL="http://www.belkin.com/plugin/"
manufacturer="Belkin International Inc."
deviceType="urn:Belkin:device:AirPurifier:1"
firmwareVersion="WeMo_WW_2.00.10486.PVT-OWRT-Smart"
iconVersion="1|49153"
manufacturerURL="http://www.belkin.com"
UDN="uuid:AirPurifier-1_0-221424S00002F2"
modelNumber="1.0"
UPC="123456789"

Just a heads up for those who have multiples of the non-standard Wemo Appliances.

**Comment by devbobo** [comment]
G'day @Zeate22211,

The main issue here is that Homebridge by default uses the `Name` field to generate a GUID (eg: `a113195d-ba23-4ac5-a8bb-8922a4e6aef6` from your error message), so as a result you get a collision because these two devices are named the same inside Homebridge.

Several months ago, I rewrote the `Wemo` plugin to work with the Homebridge plugin infrastructure in version `0.3.0`, when I rewrote this I based the GUID generation off `macAddress` instead of `friendlyName` which in this case should prevent the issue you are seeing.

Unfortunately, @rudders hasn't merged my changes into the `master` branch of the plugin yet, but you can get it from [here](https://github.com/rudders/homebridge-platform-wemo/tree/persist-homekit)

A word of warning, running the name code will result in your devices being regenerated within HomeKit as a new GUID will be generated for each device.

Hope this helps.

Cheers,

David

**Comment by devbobo** [comment]
This issue should be resolved with the new `1.0.0` release
