### ISSUE TITLE
Garage opener for WeMo maker

### ISSUE THREAD

**Issue by julien94800** [rudders/homebridge-platform-wemo#62]
Hello, is there a way to define the maker as a garage opener instead of a switch?
I am too looking for a way to add the sensor of the maker as a sensor independant of the control button. By this way, it would be possible to quickly show the state of the sensor (in iOS control center) whitout to go inside the switch status. 

Thanks in advance

**Comment by devbobo** [comment]
G'day Julien,

If you grab the latest code from [here] (https://raw.githubusercontent.com/rudders/homebridge-platform-wemo/master/index.js), it nows creates it's own `ContactSensor` if it been set as 'yes` in the WeMo app.

It should be possible to switch it from a `Switch` to a `Garage Opener` but I need to do more investigation into that service.

**Comment by julien94800** [comment]
Hello,

Thanks for your answer. I tried using the new code but I get this error at the start:
"Cannot add a Service with the same UUID as another Service in this Accessory without also defining a unique subtype property. Do you get the same thing?

**Comment by devbobo** [comment]
oh, you need to upgrade to the latest version of Homebridge (at least `0.4.1`)

**Comment by devbobo** [comment]
@julien94800 did you manage to get it working ?

**Comment by julien94800** [comment]
Hello,
No, I am at the latest version but still the same problem. I tried deleting completely the bridge and tried again but still the same issue. It only works if I disable the sensor in the wemo app. I will try again to be sure

**Comment by devbobo** [comment]
how did you upgrade to the latest version ? npm install or git ? If you pulled the latest git, did you run `npm install` in the `homebridge` directory ? As a new version of `HAP-NodeJS` needs to be installed as well.

**Comment by hauweit** [comment]
It certainly seems possible to set a Maker up as a `GarageDoorOpener` service instead of a `Switch` and `ContactSensor`. Otherwise Siri doesn't seem to work when I asks it to open the garage door.

1. Set up Maker as single `GarageDoorOpener` service which will inherit the following mandatory characteristics:
- `CurrentDoorState`
- `TargetDoorState`
- `ObstructionDetected` 

2. Map `CurrentDoorState` to the Maker sensor 
- This characteristic considers a 0 = OPEN and 1 = CLOSED
- We won't be able to support the other status `OPENING`, `CLOSING`, `STOPPED` as the Maker sensor only provides a binary reading.
- So therefore a Maker `Sensor` value of `0` or `1` when read off `getAttributes` can have a direct correlation to the sensor state (depends on the polarity of the sensor wiring). This may need some kind of a config parameter perhaps?

3. Map `TargetDoorState` to action the Maker switch
- This may be tricky as the Maker switch has two modes: Toggle or Momentary
- Toggle works like the standard Wemo switch (On or Off and stays in that state).
- Momentary flicks from On to Off within about 1 second.
- The Maker `SwitchMode` attribute will be set to 0 = Toggle and 1 = Momentary so perhaps some intelligent behavioural change can be written up by reading this setting.
- To open/stop/close garage door, send a `1` using `setBinaryState` which will cause the Maker to momentarily make the switch go from "on-off" My opener behaves this way and I assume is a common behaviour.

4. Set up event handlers for `CurrentDoorState` and `TargetDoorState`
- These should then update Homekit status whenever there is an event related to these two characteristics which may happen outside of Homekit (e.g. manufacturer remote control operation, manual override)
- To action the Maker whenever there is an intended `TargetDoorState` change

We probably won't be able to map `ObstructionDetected` to anything as the Maker only has one sensor input.

Hope I'm on the right track but alas, I'm not a good enough coder to implement this gracefully.

**Comment by julien94800** [comment]
@devbobo Thanks again for your support. I made some new tests and it now works as expected. I do not understand what happened during my previous install.

**Comment by julien94800** [comment]
Hello @hauweit ,

Thanks for your explanation. I think you are right for the scenario. Using the sensor to deals with the current status is the  only way to get something perfect. Currently, my only way to open and or close the door is to tell Siri (open the garage door). Indeed, as I am in "momentary" mode, at each update status, my swith is set back to off. So if I ask Siri to close the door, it always answer back "already closed". I think most of the maker for garage door are used in "momentary" mode because it is commonly wired as a push button into the motor. For obstructiondetected, it could work by using a second maker but it will then become expensive and complicated to deals with. I think that most of the code is already wrote in this current tool but it can become complex to reorder all for a good working. Of course, too complex for me, but it should not be for @devbobo 

Thanks again for all your works

**Comment by devbobo** [comment]
@hauweit thanks, I'm aware that it could be configured the `GarageDoorOpener`. What I was alluding to was using the extensions that @khaost put into Homebridge so what devices can be change or modified using Hesperus to add/modify/remove service/accessories.

Anyhow, made some great progress today. @hauweit, your assessment is pretty close, but there are a few cornercases that you didn't touch on.

Handling the following events...
- opening/closing the garage door with an external door
- opening/closing the garage door with the button on the WeMo maker

I have the major of scenarios...but right now I'm ignoring the `stop` functionality, as I currently don't have the WeMo Maker connected. I'm hoping to get that sorted this week sometime.

**Comment by hauweit** [comment]
@devbobo Oops, I did miss listing out adding a listener for `Sensor` state changes which would then update the `CurrentDoorState` characteristic. That should cater for real-time status updates due to external events like what you've mentioned.

My garage door opener cycles through the open/stop/close on each external remote button/Maker button press so I don't think there should be any other special handling that's required, it seems to be the same input (circuit close and open).

I'm curious on how the Homebridge extensions and Hesperus configuration can work. That may be a more elegant way of configuring Makers since it is such a versatile device.

@julien94800 Yes, I suppose a second Maker is possible but I suspect it may become quite a bit more complex trying to fuse sensor inputs from two different devices, not to mention extra cost as you say. Most openers should have a "back off" safety feature when an obstruction is detected during closing anyway, so this may not be a big deal.

**Comment by devbobo** [comment]
I've managed to get configuration switching logic working.

When homebridge initially launches and get everything going, any WeMo maker instances requests it's parameters.

If `SwitchMode` == `Momentary`, I configure the device as `Service.GarageDoorOpener`.

If `SwitchMode` == `Toggle`, I configure the device as `Service.Switch`. Additionally, if `SensorPresent` == 1, I also add `Service.ContactSensor`.

If the parameters have changed on the next restart, the services are reconfigured.

Making good progress, hoping I might be able to push a release with this functionality some time this week.

**Comment by julien94800** [comment]
Very good news. Thanks again for your work!

**Comment by devbobo** [comment]
@julien94800 @hauweit please try out `1.1.0`

**Comment by hauweit** [comment]
@devbobo That really looks like a big update to the codebase indeed! Will try it out tonight and post back.

**Comment by julien94800** [comment]
Hello @devbobo
It seems to work perfectly but not sure about all because I have my maker currently wired without any sensor. I should fix it today (wire my sensor) so I will be able to made fully test just after. Currently, I do not understand how it can says if my door is opened or closed. It seems it only change state from current one each time that I activate the door from home app. 
Furthermore, I now get an "allow notifications" setting under the garage door button in home app. Do you know what are these notifications? I haven't this setting before and I have not this under other device. 
Thanks again for your hard work

**Comment by devbobo** [comment]
@julien94800 currently, if `Sensor` is set to `No`, I generate the states based off a timer of around 20 seconds. Once you have wired your sensor and set `Sensor` to `Yes` in the WeMo app. Restart homebridge and it will start using the sensor for knowing `Closed` position.

The "allow notifications" option will push a notification to your iphone whether the status of the door changes.

Not sure what version you ended up with, but make you get `1.1.1`, it has some other fixes in it.

**Comment by hauweit** [comment]
Hi @devbobo, I've just put in 1.1.1 and it looks like my sensor wiring is the reverse of what is coded. When my door is closed, Homebridge reports it as `Open`, my sensor reading is `1` for closed.

[10/4/2016, 7:53:38 PM] [WeMo Platform] Garage Door - Get Current Door State: Open _{Door actually closed}_
**{Press Garage Door in Home app}**
[10/4/2016, 7:55:30 PM] [WeMo Platform] Garage Door - Set Target Door State: Closed (triggered by HomeKit)
[10/4/2016, 7:55:30 PM] [WeMo Platform] Garage Door - Get Current Door State: Closing _{Door actually opening}_
[10/4/2016, 7:55:32 PM] [WeMo Platform] Garage Door - Get Current Door State: Closed
[10/4/2016, 7:55:46 PM] [WeMo Platform] Garage Door - Get Current Door State: Closed _{Door actually open}_
**{Press Garage Door in Home app}**
[10/4/2016, 7:56:54 PM] [WeMo Platform] Garage Door - Set Target Door State: Open (triggered by HomeKit) _{Door actually closing}_
[10/4/2016, 7:57:09 PM] [WeMo Platform] Garage Door - Get Current Door State: Open
[10/4/2016, 7:57:20 PM] [WeMo Platform] Garage Door - Get Current Door State: Open _{Door actually closed}_

I wonder if I need to re-wire my sensor? It's showing "Not triggered" in the Wemo app when closed.

**Comment by devbobo** [comment]
@hauweit yes, I'd suggest rewiring. I'd prefer to go with what the WeMo app is reporting than to add options to reconfigure that in case something gets messed up.

**Comment by julien94800** [comment]
What is strange is that I used the maker set with sensor to yes, even if I do not wired my sensor. So the state should be always open?  How is the state defined? If for example I open manually the door, will the state been automatically updated in homebridge or it is updated only when activate?

**Comment by devbobo** [comment]
The `Sensor` is set to `yes` in the WeMo app but no sensor is present, it probably won't work.

If the `Sensor` is set to `no` in the WeMo app, but `Closed` state will be calculated based off the timer expiring like `Open`.

If you have a `Sensor` attached and you manually trigger it using a remote, it should work out what state it is in. I'm working on an update which should refine this a little bit.

**Comment by julien94800** [comment]
Thanks for the answer. I will try this evening with version 1.1.1 (I only tried with 1.1 this morning) and my sensor correctly wired in order to be sure to understand everything.

**Comment by devbobo** [comment]
@hauweit  @julien94800 I just pushed a minor update (`1.1.2`), which should improve the robustness of the `CurrentDoorState` when a Sensor is present.

**Comment by hauweit** [comment]
@devbobo I've reverse my contact sensor polarity and it's working perfectly with `1.1.2` now. You're awesome!

It handles both HomeKit triggers and external triggers (even when mixed) just nicely. Big thumbs up! 👍 👍

**Comment by devbobo** [comment]
@hauweit awesome...glad it's working

**Comment by julien94800** [comment]
It seems to work perfectly! Very good job! Only trouble, one of my maker can not anymore be linked to the network... (not cause by homebridge). And I do not know what I can do. I try the reset button several times without success!

**Comment by devbobo** [comment]
@julien94800 yeah, they can be a pain to get on the network sometimes.

closing this issue.
